server:
  port: ${PORT:8082}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: maria
    password: 123
    url: jdbc:postgresql://localhost:5432/photoService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        type: trace